import type { NextPage } from 'next';
import Head from 'next/head';
import { trpc } from '../utils/trpc';
import { useSession, signIn, signOut } from 'next-auth/react';
import { Box, Button } from '@chakra-ui/react';
import NavBar from './components/NavBar';

const Home: NextPage = () => {
  const { data, isLoading } = trpc.useQuery([
    'example.hello',
    { text: 'from tRPC' },
  ]);

  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box>
        <NavBar />
      </Box>
    </>
  );
};

export default Home;
